packages:
  - 'packages/*'
  - 'packages/contrlibs/*'
  - 'examples/*'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@rsdoctor/client@1.5.17'
  - '@rsdoctor/core@1.5.17'
  - '@rsdoctor/graph@1.5.17'
  - '@rsdoctor/rspack-plugin@1.5.17'
  - '@rsdoctor/sdk@1.5.17'
  - '@rsdoctor/types@1.5.17'
  - '@rsdoctor/utils@1.5.17'
  - '@module-federation/bridge-react-webpack-plugin@2.7.0'
  - '@module-federation/cli@2.7.0'
  - '@module-federation/dts-plugin@2.7.0'
  - '@module-federation/enhanced@2.7.0'
  - '@module-federation/error-codes@2.7.0'
  - '@module-federation/inject-external-runtime-core-plugin@2.7.0'
  - '@module-federation/managers@2.7.0'
  - '@module-federation/manifest@2.7.0'
  - '@module-federation/rspack@2.7.0'
  - '@module-federation/runtime-core@2.7.0'
  - '@module-federation/runtime-tools@2.7.0'
  - '@module-federation/runtime@2.7.0'
  - '@module-federation/sdk@2.7.0'
  - '@module-federation/third-party-dts-extractor@2.7.0'
  - '@module-federation/webpack-bundler-runtime@2.7.0'
  - '@typescript/typescript-aix-ppc64@7.0.2'
  - '@typescript/typescript-darwin-arm64@7.0.2'
  - '@typescript/typescript-darwin-x64@7.0.2'
  - '@typescript/typescript-freebsd-arm64@7.0.2'
  - '@typescript/typescript-freebsd-x64@7.0.2'
  - '@typescript/typescript-linux-arm64@7.0.2'
  - '@typescript/typescript-linux-arm@7.0.2'
  - '@typescript/typescript-linux-loong64@7.0.2'
  - '@typescript/typescript-linux-mips64el@7.0.2'
  - '@typescript/typescript-linux-ppc64@7.0.2'
  - '@typescript/typescript-linux-riscv64@7.0.2'
  - '@typescript/typescript-linux-s390x@7.0.2'
  - '@typescript/typescript-linux-x64@7.0.2'
  - '@typescript/typescript-netbsd-arm64@7.0.2'
  - '@typescript/typescript-netbsd-x64@7.0.2'
  - '@typescript/typescript-openbsd-arm64@7.0.2'
  - '@typescript/typescript-openbsd-x64@7.0.2'
  - '@typescript/typescript-sunos-x64@7.0.2'
  - '@typescript/typescript-win32-arm64@7.0.2'
  - '@typescript/typescript-win32-x64@7.0.2'
  - tsdown@0.22.4
  - typescript@7.0.2
  - vite@8.1.4
  - tsdown@0.22.12
  - verkit@0.1.0
